export enum Job {
    DEVELOPPEUR_FRONTEND = "Développeur Frontend",
    DEVELOPPEUR_BACKEND = "Développeur Backend",
    DEVELOPPEUR_FULL_STACK = "Développeur Full Stack",
    DEVELOPPEUR_MOBILE = "Développeur Mobile (iOS / Android)",
    DEVELOPPEUR_WEB = "Développeur Web",
    DEVELOPPEUR_LOGICIEL_APPLICATION = "Développeur Logiciel / Application",
    INGENIEUR_QA_TESTEUR_LOGICIEL = "Ingénieur QA / Testeur logiciel",
    DATA_SCIENTIST = "Data Scientist",
    DATA_ANALYST = "Data Analyst",
    DATA_ENGINEER = "Data Engineer",
    MACHINE_LEARNING_ENGINEER = "Machine Learning Engineer",
    INGENIEUR_BIG_DATA = "Ingénieur Big Data",
    INGENIEUR_DEVOPS = "Ingénieur DevOps",
    INGENIEUR_CLOUD = "Ingénieur Cloud (AWS / Azure / GCP)",
    ADMINISTRATEUR_SYSTEMES_RESEAUX = "Administrateur Systèmes & Réseaux",
    ARCHITECTE_IT_ARCHITECTE_CLOUD = "Architecte IT / Architecte Cloud",
    EXPERT_CYBERSECURITE = "Expert Cybersécurité",
    UX_DESIGNER = "UX Designer",
    UI_DESIGNER = "UI Designer",
    PRODUCT_DESIGNER = "Product Designer",
    PRODUCT_OWNER = "Product Owner",
    PRODUCT_MANAGER = "Product Manager",
    SCRUM_MASTER = "Scrum Master",
    CHEF_DE_PROJET_IT = "Chef de projet IT",
    BUSINESS_ANALYST = "Business Analyst",
}