export enum Skill {
  FRONTEND = 'Frontend (React, Angular, Vue.js, Svelte…)',
  BACKEND = 'Backend (Java, Python, Node.js, PHP, .NET, Ruby…)',
  MOBILE_DEVELOPMENT = 'Mobile Development (iOS, Android, Flutter, React Native…)',
  FULLSTACK_DEVELOPMENT = 'Fullstack Development',
  LOW_CODE_NO_CODE = 'Low-code / No-code',
  DATA_ENGINEERING = 'Data Engineering (ETL, Big Data, Spark, Hadoop…)',
  DATA_SCIENCE_ML = 'Data Science & Machine Learning',
  AI_DEEP_LEARNING = 'Artificial Intelligence & Deep Learning (NLP, Computer Vision…)',
  BUSINESS_INTELLIGENCE = 'Business Intelligence (Power BI, Tableau, Qlik…)',
  CLOUD_COMPUTING = 'Cloud Computing (AWS, Azure, GCP)',
  DEVOPS_CI_CD = 'DevOps / CI-CD (Docker, Kubernetes, Terraform…)',
  INFRASTRUCTURE_AS_CODE = 'Infrastructure as Code',
  SYSTEMS_ADMINISTRATION = 'Systems Administration (Linux, Windows, Unix)',
  NETWORKS_TELECOMMUNICATIONS = 'Networks & Telecommunications',
  DATABASES = 'Databases',
  VIRTUALIZATION_CONTAINERIZATION = 'Virtualization & Containerization',
  PRODUCT_MANAGEMENT = 'Product Management',
  AGILE_METHODOLOGIES = 'Agile / Scrum / Kanban Methodologies',
  IT_PROJECT_MANAGEMENT = 'IT Project Management',
  BUSINESS_ANALYSIS = 'Business Analysis',
  UI_UX_DESIGN = 'UI/UX Design',
  WEB_DESIGN_INTEGRATION = 'Web Design & Integration',
  PROTOTYPING = 'Prototyping (Figma, Sketch, Adobe XD)',
}
